### ISSUE TITLE
An error has occured while updating device

### ISSUE THREAD

**Issue by ghost** [ExistOS-Team/ExistOS_Updater_v2#1]
Hello. I am using Windows 10 and could install ExistOS and OSLoader without any problem two firmwares ago, but now I get an error saying "An error has occured while updating device" after the updater tells me to reboot and reconnect device. It seems to be unable to detect the calculator after reconnecting it. I tried holding ON when doing it to no avail. 

I also had the same problem with older firmwares. Only 0.6.0 from two days ago wouldn't refuse to install so far.

**Comment by Edge2020** [comment]
There are some bugs with Github Action few commits ago, which will make the OSLoader unable to boot. But now it had been fixed. May you can try to use the newer firmwares?

**Comment by ghost** [comment]
I tried the new firmware and it worked on first try. Thank you
