### ISSUE TITLE
提示Device no response

### ISSUE THREAD

**Issue by reiyawea** [ExistOS-Team/ExistOS_Updater_v2#2]
我按照readme所列步骤，使用updater刷机。
可以把loader刷入RAM并自动重启，计算器显示“找不到系统”画面。
之后写入flash即提示无响应，但最终仍会弹出成功对话框（请看附图）。
尝试了多个版本的updater和固件（loader和system都来自同一release），均是如此现象。
操作系统为win10。
还望提供一些解决思路。感谢！
附图：
![捕获](https://user-images.githubusercontent.com/17851771/190360235-fc27ecc7-61ff-4dac-8687-ab144332fb74.PNG)

**Comment by Edge2020** [comment]
_这个提示刷机成功的对话框是个bug，将会尽快修复。_

### 对于此种无法正常刷入的情况，有以下几点建议：

- 检查后台有无虚拟机运行，设备重新连接时可能会被虚拟机拦截。
- 检查USB线缆是否连接牢固。
- 检查计算器电量是否充足。
- 使用官方工具正常刷回原版系统后再尝试刷入ExistOS。

如果以上操作都无法解决问题，或许可以尝试更换设备进行刷入。

**不知能否向我们提供更多系统的信息？**

### 还有几个比较繁琐的方法可以尝试：

- 使用 [这个](https://github.com/ExistOS-Team/ExistOS_Updater_v2/files/9576364/installer.zip) 散装安装包尝试刷入。

- 在win7虚拟机中安装官方升级工具，然后使用其 Firmware Updater 刷入 OSLoader（将编译的 OSLoader.sb 重命名为 firmware.sb 并替换官方固件 firmware.sb，确保文件名相同）。之后再正常连接设备，使用ExistOS Updater的EDB模式来刷入System。

**Comment by Edge2020** [comment]
对于Device no response这个错误来说，此时Updater已经检测到设备在自动重启后重新连接了，但edb协议没有响应。这有可能是由计算器死机或者电脑上某个软件引起的（比如杀毒软件拦截）。
建议在系统后台相对干净的时候再次尝试一下。

还有，请确保Options菜单中edb Mode选定为Bin Mode。

**Comment by reiyawea** [comment]
上述是在公用工作机上操作的，我换用自己的电脑就刷成功了。原因应该如您所说，在重新连接过程被杀软啥的介入了。
十分抱歉，给你们添麻烦了。

**Comment by reiyawea** [comment]
附上成功刷入的截图，以供后人参考
![捕获](https://user-images.githubusercontent.com/17851771/192090686-7bc9be14-581e-4a48-8ec0-73b897623778.PNG)
